### ISSUE TITLE
Suggestion: Edit Python logo to be white

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/kcoder63.github.io#14]
In the Skills section:
![image](https://user-images.githubusercontent.com/46727048/117149691-0ddc7100-ad7d-11eb-8cba-20fec0db446d.png)

Python's logo is in it original color (blue and yellow) while all the other logos are white, which makes an strange inconsistency. I suggest to edit the Python's logo and make it white.

**Comment by starlightknown** [comment]
I couldn't find the the fa fa logo of python but I'll find something similar and fix it

**Comment by starlightknown** [comment]
changes done
