### ISSUE TITLE
Suggestion: Add Flask logo

### ISSUE THREAD

**Issue by GaryHilares** [kcoder63/kcoder63.github.io#15]
In the Skills section:
![image](https://user-images.githubusercontent.com/46727048/117150558-dde19d80-ad7d-11eb-91da-58568d4699d7.png)

Flask is the only technology which does not have a logo, which makes an inconsistency with others. I suggest to add the Flask logo.

**Comment by starlightknown** [comment]
Yep same reason as the python one, will fix it with something else

**Comment by starlightknown** [comment]
closed via #22
