### ISSUE TITLE
Provide link to your resume

### ISSUE THREAD

**Issue by vikasganiga05** [kcoder63/kcoder63.github.io#26]
Add a button on the hero section to view or download your resume ( `myresume.pdf` ) file on [starlightknown.github.io](https://starlightknown.github.io/).

#### Screenshot
![image](https://user-images.githubusercontent.com/74750414/160239200-2c952327-dd98-4a78-a920-4b7f8c4807f8.png)

**Comment by starlightknown** [comment]
![image](https://user-images.githubusercontent.com/74637789/160265161-7b6a4680-e623-4d69-a29b-0bf6f8209c95.png)
 yeah that could be done, I added the link here in case you didnt notice

**Comment by vikasganiga05** [comment]
> ![image](https://user-images.githubusercontent.com/74637789/160265161-7b6a4680-e623-4d69-a29b-0bf6f8209c95.png) yeah that could be done, I added the link here in case you didnt notice

Yeah! you're right I missed that. Should I close this issue or not?
